# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_python2to3_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureusage',
            name='count',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usage',
            name='osVersion',
            field=models.CharField(max_length=64),
        ),
    ]
