FROM postgres:latest
RUN mkdir -p /tmp/psql_data/
#COPY previous_data.sql /tmp/psql_data/structure.sql
#COPY previous_data.sql /docker-entrypoint-initdb.d/
#COPY scripts/init_user_db.sh /docker-entrypoint-initdb.d/
#COPY scripts/init_docer_postgres.sh /docker-entrypoint-initdb.d/
